### ISSUE TITLE
HTML/JS - Login Screen (soundcloud or guest)

### ISSUE THREAD

**Issue by alexhgian** [sethachoi/soundstorm#3]
- [x] HTML implementation of the Login Screen
- [x] JS implementation of the Login Screen

The basic login screen is there but you job is to make it awesome!

Location: 
<img width="289" alt="screenshot 2016-02-03 16 46 10" src="">

**Comment by alexhgian** [comment]
#

**Comment by sethachoi** [comment]
SC auth works but now we need guest login (just a username I imagine)
